// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO9tY98h3L7XlsbBhAD4W0ERJdq32fnZ4',
    appId: '1:677196067286:web:be48ba4ee0e193ba247477',
    messagingSenderId: '677196067286',
    projectId: 'mehmetcanmovies',
    authDomain: 'mehmetcanmovies.firebaseapp.com',
    storageBucket: 'mehmetcanmovies.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_WVMT-eg7bCJTDADfYAhX-5jWvJT8zo',
    appId: '1:677196067286:android:b5cc4bd41b2512c4247477',
    messagingSenderId: '677196067286',
    projectId: 'mehmetcanmovies',
    storageBucket: 'mehmetcanmovies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4kUf9vvc4kY9vqas9zB06wpqbRTlMvQ',
    appId: '1:677196067286:ios:1cfc70c1dfa73763247477',
    messagingSenderId: '677196067286',
    projectId: 'mehmetcanmovies',
    storageBucket: 'mehmetcanmovies.appspot.com',
    iosClientId: '677196067286-dlgg3v8nhj5e6gh454l0eophmnb8lokt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehmetcanmovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4kUf9vvc4kY9vqas9zB06wpqbRTlMvQ',
    appId: '1:677196067286:ios:cca04494480a4c9f247477',
    messagingSenderId: '677196067286',
    projectId: 'mehmetcanmovies',
    storageBucket: 'mehmetcanmovies.appspot.com',
    iosClientId: '677196067286-5ino8fqrdqhma6oni2hh6d8l4ruq7gc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehmetcanmovies.RunnerTests',
  );
}
